---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves

Did gyre and gimble in the wabe:

All mimsy were the borogoves,

And the mome raths outgrabe.


## Second Verse
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Brown lived at such a lofty farm

That everyone for miles could see

His lantern when he did his chores

In winter after half-past three.

## Third Verse
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

"The sun was shining on the sea,

 Shining with all his might:
 
He did his very best to make

The billows smooth and bright —

And this was odd, because it was

The middle of the night

## Last Verse
Twinkle, twinkle, little star, 

How I wonder what you are! 

Up above the world so high, 

Like a diamond in the sky. 


When the blazing sun is gone, 

When he nothing shines upon, 

Then you show your little light, 

Twinkle, twinkle, all the night.
